src/IS4.Admin/Controllers/ConfigurationController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Helpers;
using Skoruba.IdentityServer4.Admin.BusinessLogic.Services.Interfaces;
using IS4.Admin.Configuration.Constants;
using Skoruba.IdentityServer4.Admin.EntityFramework.DbContexts;
using IS4.Admin.ExceptionHandling;

namespace IS4.Admin.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    public class ConfigurationController : BaseController
    {
        private readonly IIdentityResourceService<AdminDbContext> _identityResourceService;
        private readonly IApiResourceService<AdminDbContext> _apiResourceService;
        private readonly IClientService<AdminDbContext> _clientService;
        private readonly IStringLocalizer<ConfigurationController> _localizer;

        public ConfigurationController(IIdentityResourceService<AdminDbContext> identityResourceService,
            IApiResourceService<AdminDbContext> apiResourceService,
            IClientService<AdminDbContext> clientService,
            IStringLocalizer<ConfigurationController> localizer,
            ILogger<ConfigurationController> logger)
            : base(logger)
        {
            _identityResourceService = identityResourceService;
            _apiResourceService = apiResourceService;
            _clientService = clientService;
            _localizer = localizer;
        }

        [HttpGet]
        [Route("[controller]/[action]")]
        [Route("[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Client(int id)
        {
            if (id == 0)
            {
                var clientDto = _clientService.BuildClientViewModel();
                return View(clientDto);
            }

            var client = await _clientService.GetClientAsync((int)id);
            client = _clientService.BuildClientViewModel(client);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Client(ClientDto client)
        {
            client = _clientService.BuildClientViewModel(client);

            if (!ModelState.IsValid)
            {
                return View(client);
            }

            //Add new client
            if (client.Id == 0)
            {
                var clientId = await _clientService.AddClientAsync(client);
                SuccessNotification(string.Format(_localizer["SuccessAddClient"], client.ClientId), _localizer["SuccessTitle"]);

                return RedirectToAction(nameof(Client), new { Id = clientId });
            }

            //Update client
            await _clientService.UpdateClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessUpdateClient"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { client.Id });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClone(int id)
        {
            if (id == 0) return NotFound();

            var clientDto = await _clientService.GetClientAsync(id);
            var client = _clientService.BuildClientCloneViewModel(id, clientDto);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClone(ClientCloneDto client)
        {
            if (!ModelState.IsValid)
            {
                return View(client);
            }

            var newClientId = await _clientService.CloneClientAsync(client);
            SuccessNotification(string.Format(_localizer["SuccessClientClone"], client.ClientId), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Client), new { Id = newClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientDelete(int id)
        {
            if (id == 0) return NotFound();

            var client = await _clientService.GetClientAsync(id);

            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientDelete(ClientDto client)
        {
            await _clientService.RemoveClientAsync(client);

            SuccessNotification(_localizer["SuccessClientDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(Clients));
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaims(int id, int? page)
        {
            if (id == 0) return NotFound();

            var claims = await _clientService.GetClientClaimsAsync(id, page ?? 1);

            return View(claims);
        }

        [HttpGet]
        public async Task<IActionResult> ClientProperties(int id, int? page)
        {
            if (id == 0) return NotFound();

            var properties = await _clientService.GetClientPropertiesAsync(id, page ?? 1);

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientProperties(ClientPropertiesDto clientProperty)
        {
            if (!ModelState.IsValid)
            {
                return View(clientProperty);
            }

            await _clientService.AddClientPropertyAsync(clientProperty);
            SuccessNotification(string.Format(_localizer["SuccessAddClientProperty"], clientProperty.ClientId, clientProperty.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientProperties), new { Id = clientProperty.ClientId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientClaims(ClientClaimsDto clientClaim)
        {
            if (!ModelState.IsValid)
            {
                return View(clientClaim);
            }

            await _clientService.AddClientClaimAsync(clientClaim);
            SuccessNotification(string.Format(_localizer["SuccessAddClientClaim"], clientClaim.Value, clientClaim.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientClaims), new { Id = clientClaim.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientClaimDelete(int id)
        {
            if (id == 0) return NotFound();

            var clientClaim = await _clientService.GetClientClaimAsync(id);

            return View(nameof(ClientClaimDelete), clientClaim);
        }

        [HttpGet]
        public async Task<IActionResult> ClientPropertyDelete(int id)
        {
            if (id == 0) return NotFound();

            var clientProperty = await _clientService.GetClientPropertyAsync(id);

            return View(nameof(ClientPropertyDelete), clientProperty);
        }

        [HttpPost]
        public async Task<IActionResult> ClientClaimDelete(ClientClaimsDto clientClaim)
        {
            await _clientService.DeleteClientClaimAsync(clientClaim);
            SuccessNotification(_localizer["SuccessDeleteClientClaim"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientClaims), new { Id = clientClaim.ClientId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientPropertyDelete(ClientPropertiesDto clientProperty)
        {
            await _clientService.DeleteClientPropertyAsync(clientProperty);
            SuccessNotification(_localizer["SuccessDeleteClientProperty"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientProperties), new { Id = clientProperty.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientSecrets(int id, int? page)
        {
            if (id == 0) return NotFound();

            var clientSecrets = await _clientService.GetClientSecretsAsync(id, page ?? 1);
            _clientService.BuildClientSecretsViewModel(clientSecrets);

            return View(clientSecrets);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientSecrets(ClientSecretsDto clientSecret)
        {
            await _clientService.AddClientSecretAsync(clientSecret);
            SuccessNotification(string.Format(_localizer["SuccessAddClientSecret"], clientSecret.ClientName), _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientSecrets), new { Id = clientSecret.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> ClientSecretDelete(int id)
        {
            if (id == 0) return NotFound();

            var clientSecret = await _clientService.GetClientSecretAsync(id);

            return View(nameof(ClientSecretDelete), clientSecret);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClientSecretDelete(ClientSecretsDto clientSecret)
        {
            await _clientService.DeleteClientSecretAsync(clientSecret);
            SuccessNotification(_localizer["SuccessDeleteClientSecret"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(ClientSecrets), new { Id = clientSecret.ClientId });
        }

        [HttpGet]
        public async Task<IActionResult> SearchScopes(string scope, int limit = 0)
        {
            var scopes = await _clientService.GetScopesAsync(scope, limit);

            return Ok(scopes);
        }

        [HttpGet]
        public IActionResult SearchClaims(string claim, int limit = 0)
        {
            var claims = _clientService.GetStandardClaims(claim, limit);

            return Ok(claims);
        }

        [HttpGet]
        public IActionResult SearchGrantTypes(string grant, int limit = 0)
        {

src/IS4.Admin/Views/Configuration/Client/Section/ActionButtons.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer

<div class="row client">
	<div class="col-md-12 action-butons">
		<button class="client-save-button btn btn-primary">@Localizer["ButtonSave"]</button>

		@if (Model.Id != 0)
		{
			<a asp-action="ClientClone" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">@Localizer["ButtonClone"]</a>
			<a asp-action="ClientDelete" asp-route-id="@Model.Id" class="btn btn-danger">@Localizer["ButtonDelete"]</a>
		}
	</div>
</div>

src/IS4.Admin/Views/Configuration/Client/Section/Authentication.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PanelTitle"]</h5>
	<div class="card-body">
		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="FrontChannelLogoutUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "FrontChannelLogoutUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="FrontChannelLogoutUri">
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="FrontChannelLogoutSessionRequired" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "FrontChannelLogoutSessionRequired")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="FrontChannelLogoutSessionRequired" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="BackChannelLogoutUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "BackChannelLogoutUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="BackChannelLogoutUri">
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="BackChannelLogoutSessionRequired" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "BackChannelLogoutSessionRequired")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="BackChannelLogoutSessionRequired" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="EnableLocalLogin" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "EnableLocalLogin")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="EnableLocalLogin" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="PostLogoutRedirectUris" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "PostLogoutRedirectUris")
			</label>
			<div class="col-sm-9">
				<picker id="PostLogoutRedirectUrisItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.PostLogoutRedirectUris" 
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="IdentityProviderRestrictions" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "IdentityProviderRestrictions")
			</label>
			<div class="col-sm-9">
				<picker id="IdentityProviderRestrictionsItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.IdentityProviderRestrictions"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>
	</div>
</div>

src/IS4.Admin/Views/Configuration/Client/Section/Basics.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer
<!--Hidden -->
<input type="hidden" asp-for="Id" />

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PanelTitle"]</h5>
	<div class="card-body">
		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="Enabled" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Enabled")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="Enabled" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="Description" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Description")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="Description">
			</div>
		</div>

		<!--Select-->
		<div class="form-group row">
			<label asp-for="ProtocolType" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ProtocolType")
			</label>
			<div class="col-sm-9">
				<select asp-for="ProtocolType" asp-items="@(new SelectList(Model.ProtocolTypes,"Id","Text"))" class="form-control single-select"></select>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequireClientSecret" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequireClientSecret")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequireClientSecret" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequirePkce" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequirePkce")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequirePkce" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowPlainTextPkce" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowPlainTextPkce")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowPlainTextPkce" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowOfflineAccess" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowOfflineAccess")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowOfflineAccess" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowAccessTokensViaBrowser" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowAccessTokensViaBrowser")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowAccessTokensViaBrowser" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="AllowedScopes" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowedScopes")
			</label>
			<div class="col-sm-9">
				<picker id="AllowedScopesItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.AllowedScopes" url="@Url.Action("SearchScopes","Configuration")?scope"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>


		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="RedirectUris" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RedirectUris")
			</label>
			<div class="col-sm-9">
				<picker id="RedirectUrisItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.RedirectUris"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>

		<!--Select with tags-->
		<div class="form-group row">
			<label asp-for="AllowedGrantTypes" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowedGrantTypes")
			</label>
			<div class="col-sm-9">
				<picker id="AllowedGrantTypesItems" multiple-select="true" min-search-text="2"
						url="@Url.Action("SearchGrantTypes","Configuration")?grant"
				        selected-items="@Model.AllowedGrantTypes"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
			</div>
		</div>

		<!--Button-->
		<div class="form-group row">
			<label asp-for="ClientSecrets" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientSecrets")
			</label>
			<div class="col-sm-9">
				<a asp-action="ClientSecrets" asp-route-id="@Model.Id" target="_blank" class="btn btn-primary">@Localizer["ButtonManageClientSecrets"]</a>
			</div>
		</div>


		<!--Button-->
		<div class="form-group row">
			<label asp-for="Properties" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "Properties")
			</label>
			<div class="col-sm-9">
				<a asp-action="ClientProperties" asp-route-id="@Model.Id" target="_blank" class="btn btn-primary">@Localizer["ButtonManageClientProperties"]</a>
			</div>
		</div>
	</div>
</div>

src/IS4.Admin/Views/Configuration/Client/Section/Consent.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PageTitle"]</h5>
	<div class="card-body">
		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="RequireConsent" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "RequireConsent")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="RequireConsent" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Checkbox-->
		<div class="form-group row">
			<label asp-for="AllowRememberConsent" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "AllowRememberConsent")
			</label>
			<div class="col-sm-9">
				<toggle-button>
					<input asp-for="AllowRememberConsent" type="checkbox">
				</toggle-button>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="ClientUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="ClientUri">
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="LogoUri" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "LogoUri")
			</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" asp-for="LogoUri">
			</div>
		</div>
	</div>
</div>

src/IS4.Admin/Views/Configuration/Client/Section/Label.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model string
@inject IViewLocalizer Localizer

@Localizer[$"{Model}_Label"]
<span data-toggle="tooltip" data-original-title="@Localizer[$"{Model}_Info"]"><span style="font-size: 12px;" class="oi oi-comment-square"></span></span>

src/IS4.Admin/Views/Configuration/Client/Section/Name.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Enums
@model Skoruba.IdentityServer4.Admin.BusinessLogic.Dtos.Configuration.ClientDto
@inject IViewLocalizer Localizer

<div class="card mt-3">
	<h5 class="card-header">@Localizer["PanelTitle"]</h5>
	<div class="card-body">

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="ClientId" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientId")
			</label>
			<div class="col-sm-9">
				<input type="text" required class="form-control" asp-for="ClientId">
				<span asp-validation-for="ClientId" class="text-danger"></span>
			</div>
		</div>

		<!--Input - text -->
		<div class="form-group row">
			<label asp-for="ClientName" class="col-sm-3 col-form-label">
				@await Html.PartialAsync("Client/Section/Label", "ClientName")
			</label>
			<div class="col-sm-9">
				<input type="text" required class="form-control" asp-for="ClientName">
				<span asp-validation-for="ClientName" class="text-danger"></span>
			</div>
		</div>

		@if (Model.Id == 0)
		{			
			<div class="card-deck mb-3 text-center">
				<div class="card mt-4 mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" checked="checked" value="@((int)ClientType.Empty)" />
							<img src="~/images/icons/empty-client.png" alt="Empty" />
							<h3>@Localizer["TitleEmpty"]</h3>
						</label>
					</div>
				</div>
				<div class="card mt-4 mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" value="@((int)ClientType.WebImplicit)" />
							<img src="~/images/icons/web-client.png" alt="Web Implicit" />
							<h3>@Localizer["TitleWebImplicit"]</h3>
							<h4>@Localizer["TitleImplicit"]</h4>
						</label>
					</div>
				</div>
				<div class="card mt-4 mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" value="@((int)ClientType.WebHybrid)" />
							<img src="~/images/icons/web-client.png" alt="Web Hybrid" />
							<h3>@Localizer["TitleWebHybrid"]</h3>
							<h4>@Localizer["TitleHybrid"]</h4>
						</label>
					</div>
				</div>
			</div>

			<div class="card-deck mb-3 text-center">
				<div class="card mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" value="@((int)ClientType.Spa)" />
							<img src="~/images/icons/spa-client.png" alt="Web Spa" />
							<h3>@Localizer["TitleSpa"]</h3>
							<h4>@Localizer["TitleImplicit"]</h4>
						</label>
					</div>
				</div>
				<div class="card mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" value="@((int) ClientType.Native)" />
							<img src="~/images/icons/native-client.png" alt="Native" />
							<h3>@Localizer["TitleNative"]</h3>
							<h4>@Localizer["TitleHybrid"]</h4>
						</label>
					</div>
				</div>
				<div class="card mb-4 box-shadow">
					<div class="card-body">
						<label class="radio-img">
							<input type="radio" asp-for="ClientType" value="@((int)ClientType.Machine)" />
							<img src="~/images/icons/server-client.png" alt="Machine" />
							<h3>@Localizer["TitleMachine"]</h3>
							<h4>@Localizer["TitlePasswordAndClient"]</h4>
						</label>
					</div>
				</div>
			</div>
		}
	</div>
</div>